routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/workbooks', 'HomeController@workbook')->name('workbook');
Route::get('/my-projects', 'HomeController@myprojects')->name('myprojects');

Route::resource('course', 'CourseController');
Route::resource('folder', 'FolderController');
Route::resource('worksheet', 'WorksheetController');
Route::resource('worksheet-filled-out', 'WorksheetFilledOutController');

Route::get('/course/ql/{co}/{id}', 'SharedCourseContentController@unique_link');
Route::get('/folder/ql/{fo}/{id}', 'SharedFolderContentController@unique_link');
Route::get('/worksheet/ql/{wo}/{id}', 'SharedWorksheetContentController@unique_link');
Route::get('/worksheet-clone/{id}', 'WorksheetController@worksheet_clone');
Route::post('/updateEnrollment', 'WorksheetController@updateEnrollment');

// Handle routes or models not found methods. 
Route::fallback(function(){
    return response()->view('errors.404', [], 404);
})->name('fallback');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

@if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
@endif

<p>Want to create your own <strong>Workbooks?</strong> Become a course instructor <a href="#">Sign up!</a></p>

<p>Maybe add more promo stuff here, or dates to webinars, promo videos, etc...</p>

@if(Auth::user()->hasRole('superadmin') || Auth::user()->hasRole('teacher'))
    <a href="{{ route('course.index') }}">View all Courses</a> | 
    <a href="{{ route('course.create') }}" class="">Create course </a>
@endif



@endsection


@section('scripts')

<script type="text/javascript">

function addFolder() {

    if ($('#add_name').length == 0) {
        $('#folder_container').append(
            '<div class="col col-sm-2 col-md-2 col-lg-1"><i class="fa fa-folder fa-4x"></i><input id="add_name" type="text" name="name" class="col-md-12 p-0" autocomplete="off"/><button class="col-md-6 btn btn-sm btn-primary mt-1" onclick="saveName(this)"><i class="fa fa-save"></i></button><button class="col-md-6 btn btn-sm btn-danger mt-1" onclick="removeInput(this)"><i class="fa fa-times-circle"></i></button></div>'
        );

        $("#folder_container input").focus();
    }
}

function removeInput(){
    $('#add_name').parent().remove('');
}

/********************************************************
 * Save the YouTube URL to the database
 ********************************************************/
function saveName(data) {

    var folderName = $(data.parentElement).find('input').val();

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    $.ajax({
        method: "POST",
        url: "/folder",
        dataType: 'json',
        data: {
            name: folderName
        },
        async: false,
        success: function(data) {
            $('#add_name').parent().remove('');
            
            $('#folder_container').append('<div id="'+ data.id +'" class="col col-sm-2 col-md-2 col-lg-1"><i class="fa fa-folder fa-4x"></i> <a href="/folder/'+ data.id +'">'+ data.name +'</a> </div>');
            console.log(data);
        }
    });

}
</script>
@stop

resources/views/myprojects.blade.php
@extends('layouts.app')

@section('content')

@if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
@endif


@if(Auth::user()->hasRole('student'))
    <a href="{{ route('workbook') }}">Go to Workbooks</a>

    <hr>

    <h4 class="mb-4"> Folders 
        <button class="btn btn-primary btn-sm" onclick="addFolder()"><i class="fa fa-folder"></i> +</button>
    </h4>

    <div id="folder_container" class="row overflow-auto" >
        @foreach($folders as $folder)
        <div id="{{ $folder->id }}" class="col col-sm-2 col-md-2 col-lg-1">
            <i class="fa fa-folder fa-4x"></i>
            <a href="/folder/{{ $folder->id }}" class="block">{{ $folder->name }}</a>
        </div>
        @endforeach
    </div>  
@endif

@endsection


@section('scripts')

<script type="text/javascript">

function addFolder() {

    if ($('#add_name').length == 0) {
        $('#folder_container').append(
            '<div class="col col-sm-2 col-md-2 col-lg-1"><i class="fa fa-folder fa-4x"></i><input id="add_name" type="text" name="name" class="col-md-12 p-0" autocomplete="off"/><button class="col-md-6 btn btn-sm btn-primary mt-1" onclick="saveName(this)"><i class="fa fa-save"></i></button><button class="col-md-6 btn btn-sm btn-danger mt-1" onclick="removeInput(this)"><i class="fa fa-times-circle"></i></button></div>'
        );

        $("#folder_container input").focus();
    }
}

function removeInput(){
    $('#add_name').parent().remove('');
}

/********************************************************
 * Save the YouTube URL to the database
 ********************************************************/
function saveName(data) {

    var folderName = $(data.parentElement).find('input').val();

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    $.ajax({
        method: "POST",
        url: "/folder",
        dataType: 'json',
        data: {
            name: folderName,
            type: 'project_folders'
        },
        async: false,
        success: function(data) {
            $('#add_name').parent().remove('');
            
            $('#folder_container').append('<div id="'+ data.id +'" class="col col-sm-2 col-md-2 col-lg-1"><i class="fa fa-folder fa-4x"></i> <a href="/folder/'+ data.id +'">'+ data.name +'</a> </div>');
            console.log(data);
        }
    });

}
</script>
@stop

resources/views/workbook.blade.php
@extends('layouts.app')

@section('content')

<div class="ibox-title">
    <h5>View all your courses, folders, and worksheets</h5>
</div>

<div class="ibox-content">

    <div class="table-responsive">
        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
            <table id="DataTables_Table" class="table table-striped table-bordered table-hover dataTables-example" style="width:100%">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>You have access to</th>
                    </tr>
                </thead>
                <tbody>
                   
                    <?php 
                        $i = 0; 
                        $showCourseObject = [];
                    ?>

                    @foreach($cfw as $data )
                    <tr>
                        @if( $data->course != null )

                            @if(!in_array($data->course_id, $showCourseObject ))
                                <?php array_push($showCourseObject, $data->course_id); ?>
                                <td><a href="/course/ql/co/{{ $data->course->unique_link }}">{{ $data->course->name }}</a></td>
                                <td><span class="pr-1">Course </span></td>
                            @endif

                        @elseif( $data->folder != null )

                            @if(!in_array($data->folder_id, $showCourseObject ))
                                <?php array_push($showCourseObject, $data->folder_id); ?>
                                <td><a href="/folder/ql/fo/{{ $data->folder->unique_link }}">{{ $data->folder->name }}</a></td>
                                <td><span class="pr-2">Folder </span></td>
                            @endif
                            
                        @elseif( $data->worksheet != null)

                            @if(!in_array($data->worksheet_id, $showCourseObject ))
                                <?php array_push($showCourseObject, $data->worksheet_id); ?>
                                <td><a href="/worksheet/ql/wo/{{ $data->worksheet->unique_link }}">{{ $data->worksheet->name }}</a></td>
                                <td><span class="pr-0">Worksheet </span> </td>
                            @endif

                        @endif

                        <?php $i++; ?>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>Name</th>
                        <th>You have access to</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

@endsection

@section('scripts')
    <!-- Pages specific scripts -->
    <script src="js/plugins/dataTables/datatables.min.js"></script>
    <script src="js/plugins/dataTables/dataTables.bootstrap4.min.js"></script>
    
    <!-- Page-Level Scripts -->
    <script>
        $(document).ready(function(){
            $('#DataTables_Table').DataTable();
        });

    </script>
@stop