routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/workbooks', 'HomeController@workbook')->name('workbook');
Route::get('/my-projects', 'HomeController@myprojects')->name('myprojects');

Route::resource('course', 'CourseController');
Route::resource('folder', 'FolderController');
Route::resource('worksheet', 'WorksheetController');
Route::resource('worksheet-filled-out', 'WorksheetFilledOutController');

Route::get('/course/ql/{co}/{id}', 'SharedCourseContentController@unique_link');
Route::get('/folder/ql/{fo}/{id}', 'SharedFolderContentController@unique_link');
Route::get('/worksheet/ql/{wo}/{id}', 'SharedWorksheetContentController@unique_link');
Route::get('/worksheet-clone/{id}', 'WorksheetController@worksheet_clone');
Route::post('/updateEnrollment', 'WorksheetController@updateEnrollment');

// Handle routes or models not found methods. 
Route::fallback(function(){
    return response()->view('errors.404', [], 404);
})->name('fallback');

resources/views/partials/breadcrumb.blade.php
<!--
        <div class="row wrapper border-bottom white-bg page-heading">
            <div class="col-lg-10">
                <h2>{{ ucwords(str_replace('-',' ',Request::segment(1)))}}</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{{ route('home') }}">Home</a>
                    </li>

                    <?php $link = "" ?>
                    @for($i = 1; $i <= count(Request::segments()); $i++)
                        <li class="breadcrumb-item">
                            <strong> 
                                @if($i < count(Request::segments()) & $i > 0)
                                    <?php $link .= "/" . Request::segment($i); ?>
                                    <a href="<?= $link ?>">{{ ucwords(str_replace('-',' ',Request::segment($i)))}}</a>
                                    @else {{ucwords(str_replace('-',' ',Request::segment($i)))}}
                                @endif
                            </strong>
                        </li>
                    @endfor

                </ol>
            </div>
            <div class="col-lg-2">

            </div>
        </div>  

        -->

resources/views/partials/sidebar.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="block m-t-xs font-bold">
                        
                        {{ Auth::user()->name }}
                        
                        </span>
                    </a>
                    
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>

        @if(Auth::user()->hasRole('superadmin') || Auth::user()->hasRole('teacher'))
        <li class="{{ Request::segment(1) == 'home' ? 'active' : ''}}">
            <a href="{{ route('home') }}"><i class="fa fa-home"></i> <span class="nav-label">Home</span></a>
        </li>
        
        <li class="active">
            <a href="#" aria-expanded="true"><i class="fa fa-institution"></i> <span class="nav-label">Teacher</span><span class="fa arrow"></span></a>
            <ul class="nav nav-second-level collapse in" aria-expanded="true" style="">
                <li><a href="{{ route('course.index') }}">Courses</a></li>
                <li><a href="{{ route('worksheet.index') }}">All Worksheets</a></li>
            </ul>
        </li>
        @endif

        @if(Auth::user()->hasRole('student'))
        <li class="active">
            <a href="#" aria-expanded="true"><i class="fa fa-graduation-cap"></i> <span class="nav-label">Student</span><span class="fa arrow"></span></a>
            <ul class="nav nav-second-level collapse in" aria-expanded="true" style="">
                <li class="{{ Request::segment(1) == 'workbooks' ? 'active' : ''}}"><a href="{{ route('workbook') }}">Workbooks</a></li>
                <li class="{{ Request::segment(1) == 'projectfolders' ? 'active' : ''}}"><a href="{{ route('myprojects') }}">My Projects</a></li>
 
            </ul>
        </li>
        @endif

        </ul>

    </div>
</nav>